from decimal import Decimal

ASSET_BNB: str = "BNB"
ASSET_USDT: str = "USDT"
ASSET_FDUSD: str = "FDUSD"
ASSET_USDC: str = "USDC"
ASSET_BUSD: str = "BUSD"
ASSET_BTC: str = "BTC"
ASSET_ETH: str = "ETH"
ASSET_TRY: str = "TRY"
RAW_COMMISSION_ASSET_BASE: str = "BASE"
RAW_COMMISSION_ASSET_QUOTE: str = "QUOTE"

# Контракт 09 — все именованные константы
T_CANCEL: int = 10
T_RECONNECT: int = 1
BALANCE_CACHE_TTL: int = 30
M_BOOK: int = 5
M_BNB: int = 10
N_SNAP: int = 10
SL_EXECUTION_BUFFER: Decimal = Decimal("0.003")
MAX_SLIPPAGE_PCT: Decimal = Decimal("0.015")
TRAILING_ATR_MULTIPLIER: Decimal = Decimal("2.0")
N_DELIST: int = 3
MIN_MEANINGFUL_POSITION_LOT_MULTIPLIER: int = 3
MIN_NOTIONAL_BUFFER: Decimal = Decimal("1.2")
BASE_RISK_PCT: Decimal = Decimal("0.015")
DEFAULT_FEE_RATE: Decimal = Decimal("0.001")
DEFAULT_MIN_ORDER_VALUE: Decimal = Decimal("10")
RISK_REDUCTION_MULTIPLIER: Decimal = Decimal("0.5")
MAX_RISK_PCT_FULL: Decimal = Decimal("0.020")
MAX_RISK_PCT_EARLY: Decimal = Decimal("0.010")
MIN_RISK_PCT: Decimal = Decimal("0.0025")
SLIPPAGE_BUFFER_PCT: Decimal = Decimal("0.002")
DAILY_LOSS_LIMIT_PCT: Decimal = Decimal("0.03")
MAX_DRAWDOWN_WARNING_PCT: Decimal = Decimal("0.10")
MAX_DRAWDOWN_STOP_PCT: Decimal = Decimal("0.20")
CONSECUTIVE_LOSSES_REDUCE: int = 3
CONSECUTIVE_LOSSES_STOP: int = 5
MAX_PORTFOLIO_RISK_PCT: Decimal = Decimal("0.06")
MAX_CORRELATED_RISK_PCT: Decimal = Decimal("0.04")
MAX_SIMULTANEOUS_POSITIONS: int = 5
CORRELATION_THRESHOLD: Decimal = Decimal("0.7")
SPM_WINRATE_WARNING: Decimal = Decimal("0.30")
SPM_WINRATE_WINDOW: int = 20
SPM_PF_WARNING: Decimal = Decimal("0.8")
SPM_CONSECUTIVE_STOP: int = 7
MIN_PAIR_VOLUME_POSITION_MULTIPLIER: int = 10
MAX_POSITION_PCT_OF_HOURLY_VOLUME: Decimal = Decimal("0.01")
WF_MAX_OPTIMIZE_PARAMS: int = 2
WF_MIN_PROFITABLE_WINDOWS_PCT: Decimal = Decimal("0.50")
CONFIG_SCHEMA_VERSION: str = "1.0.0"
STRATEGY_TIMEFRAMES: tuple[str, ...] = ("5m", "15m", "30m", "1h", "4h", "1d", "1w")
PATTERN_WEIGHT_M5: Decimal = Decimal("1.0")
PATTERN_WEIGHT_M15: Decimal = Decimal("1.5")
PATTERN_WEIGHT_M30: Decimal = Decimal("2.0")
PATTERN_WEIGHT_H1: Decimal = Decimal("3.0")
PATTERN_WEIGHT_H4: Decimal = Decimal("5.0")
PATTERN_WEIGHT_D1: Decimal = Decimal("8.0")
PATTERN_WEIGHT_W1: Decimal = Decimal("13.0")
ATR_REFERENCE_PCT: Decimal = Decimal("0.02")
ATR_MULT_MIN: Decimal = Decimal("0.50")
ATR_MULT_MAX: Decimal = Decimal("1.50")
TRAILING_ACTIVATION_ATR: Decimal = Decimal("1.0")
PARTIAL_CLOSE_TRIGGER_ATR: Decimal = Decimal("1.5")
PARTIAL_CLOSE_FRACTION: Decimal = Decimal("0.50")
BINANCE_WS_BASE_URL: str = "wss://stream.binance.com:9443/ws"
BINANCE_SPOT_TESTNET_REST_BASE_URL: str = "https://testnet.binance.vision"
BINANCE_SPOT_TESTNET_WS_BASE_URL: str = "wss://stream.testnet.binance.vision/ws"
BINANCE_SPOT_TESTNET_WS_API_BASE_URL: str = "wss://ws-api.testnet.binance.vision/ws-api/v3"
BINANCE_ANNOUNCEMENTS_RSS_URL: str = "https://www.binance.com/en/support/announcement/rss"
STREAM_PING_SECONDS: int = 30
KLINE_STALE_SECONDS: int = 120
BOOK_TICKER_STALE_SECONDS: int = 15
BNB_TICKER_STALE_SECONDS: int = 30
USER_DATA_STALE_SECONDS: int = 30
PAPER_SMOKE_ORDER_QTY: Decimal = Decimal("0.010")
PAPER_RUNTIME_HEARTBEAT_SECONDS: int = 1
SPOT_BACKTEST_FREE_QUOTE_EPSILON: Decimal = Decimal("0.00000001")
ACCOUNT_SNAPSHOT_TTL_SECONDS: int = 30
USER_STREAM_KEEPALIVE_SECONDS: int = 1800
STARTUP_BOOK_BID_TIMEOUT_SECONDS: int = 5
RESTART_RECONCILIATION_BID_TIMEOUT_SECONDS: int = 5
HEARTBEAT_TIMEOUT_SECONDS: int = 10
CLOCK_DRIFT_INFO_SECONDS: int = 5
BNB_NEAR_ZERO_THRESHOLD: Decimal = Decimal("0.01")
EXECUTION_STATE_RETENTION_SECONDS: int = 3600
MAX_EXECUTION_STATE_TERMINAL_ENTRIES: int = 256
EXCHANGE_ORDER_STATUS_FILLED: str = "FILLED"
EXCHANGE_ORDER_STATUS_PARTIALLY_FILLED: str = "PARTIALLY_FILLED"
EXCHANGE_ORDER_STATUS_NEW: str = "NEW"
EXCHANGE_ORDER_STATUS_PENDING_NEW: str = "PENDING_NEW"
EXCHANGE_ORDER_STATUS_CANCELED: str = "CANCELED"
EXCHANGE_ORDER_STATUS_CANCELLED: str = "CANCELLED"
EXCHANGE_ORDER_STATUS_EXPIRED: str = "EXPIRED"
EXCHANGE_ORDER_STATUS_REJECTED: str = "REJECTED"
EXCHANGE_TERMINAL_ORDER_STATUSES: tuple[str, ...] = (
    EXCHANGE_ORDER_STATUS_FILLED,
    EXCHANGE_ORDER_STATUS_CANCELED,
    EXCHANGE_ORDER_STATUS_CANCELLED,
    EXCHANGE_ORDER_STATUS_EXPIRED,
    EXCHANGE_ORDER_STATUS_REJECTED,
)
EXCHANGE_ACTIVE_ORDER_STATUSES: tuple[str, ...] = (
    EXCHANGE_ORDER_STATUS_NEW,
    EXCHANGE_ORDER_STATUS_PENDING_NEW,
    EXCHANGE_ORDER_STATUS_PARTIALLY_FILLED,
)
EXCHANGE_OPEN_SUBMIT_ORDER_STATUSES: tuple[str, ...] = (
    EXCHANGE_ORDER_STATUS_NEW,
    EXCHANGE_ORDER_STATUS_PENDING_NEW,
)
EXCHANGE_FILLED_OR_PARTIAL_ORDER_STATUSES: tuple[str, ...] = (
    EXCHANGE_ORDER_STATUS_FILLED,
    EXCHANGE_ORDER_STATUS_PARTIALLY_FILLED,
)
EXCHANGE_LIST_STATUS_ALL_DONE: str = "ALL_DONE"
EXCHANGE_USER_DATA_EVENT_ACCOUNT_POSITION: str = "outboundAccountPosition"
EXCHANGE_USER_DATA_EVENT_EXECUTION_REPORT: str = "executionReport"
EXCHANGE_USER_DATA_EVENT_LIST_STATUS: str = "listStatus"
EXCHANGE_STATUS_SOURCE_REST: str = "rest"
EXCHANGE_STATUS_SOURCE_WEBSOCKET: str = "websocket"
EXCHANGE_WS_API_METHOD_SESSION_LOGON: str = "session.logon"
EXCHANGE_WS_API_METHOD_SESSION_LOGOUT: str = "session.logout"
EXCHANGE_WS_API_METHOD_USER_DATA_SUBSCRIBE: str = "userDataStream.subscribe"
EXCHANGE_WS_API_METHOD_USER_DATA_SUBSCRIBE_SIGNATURE: str = "userDataStream.subscribe.signature"
EXCHANGE_WS_API_METHOD_USER_DATA_UNSUBSCRIBE: str = "userDataStream.unsubscribe"
EXCHANGE_ORDER_STATUS_RANKS: dict[str, int] = {
    EXCHANGE_ORDER_STATUS_PENDING_NEW: 1,
    EXCHANGE_ORDER_STATUS_NEW: 2,
    EXCHANGE_ORDER_STATUS_PARTIALLY_FILLED: 3,
    EXCHANGE_ORDER_STATUS_REJECTED: 4,
    EXCHANGE_ORDER_STATUS_CANCELED: 5,
    EXCHANGE_ORDER_STATUS_CANCELLED: 5,
    EXCHANGE_ORDER_STATUS_EXPIRED: 5,
    EXCHANGE_ORDER_STATUS_FILLED: 6,
}
SUPPORTED_EXCHANGE_SPOT_QUOTE_ASSETS: tuple[str, ...] = (
    ASSET_USDT,
    ASSET_FDUSD,
    ASSET_USDC,
    ASSET_BUSD,
    ASSET_BTC,
    ASSET_ETH,
    ASSET_BNB,
    ASSET_TRY,
)
CRITICAL_EXTERNAL_OCO_CANCEL_CODE: str = "EXTERNAL_OCO_CANCELLED"
CRITICAL_STARTUP_PROTECTION_CONFLICT_CODE: str = "STARTUP_PROTECTION_CONFLICT"
CRITICAL_STARTUP_OCO_AMBIGUITY_CODE: str = "STARTUP_OCO_AMBIGUITY"
CRITICAL_DIRECT_SELL_OCO_CANCEL_FAILED_CODE: str = "DIRECT_SELL_OCO_CANCEL_FAILED"
CRITICAL_RESTART_OUTSTANDING_ORDER_CODE: str = "RESTART_OUTSTANDING_ORDER"
CRITICAL_RESTART_PARTIAL_FILL_CODE: str = "RESTART_PARTIAL_FILL"
CRITICAL_IP_BAN_CODE: str = "IP_BAN"
CRITICAL_RUNTIME_CRASH_CODE: str = "RUNTIME_CRASH"
CRITICAL_BACKGROUND_TASK_FAILURE_CODE: str = "BACKGROUND_TASK_FAILURE"
CRITICAL_MISSING_BASIS_CODE: str = "MISSING_BASIS"
CRITICAL_HEARTBEAT_TIMEOUT_CODE: str = "HEARTBEAT_TIMEOUT"
CRITICAL_STORAGE_UNAVAILABLE_CODE: str = "STORAGE_UNAVAILABLE"
CRITICAL_DRAWDOWN_STOP_CODE: str = "DRAWDOWN_STOP"
CRITICAL_STALE_USER_DATA_CODE: str = "STALE_USER_DATA"
WARNING_ZERO_BASIS_CODE: str = "ZERO_BASIS_DECLARED"
WARNING_MANUAL_TRADE_DETECTED_CODE: str = "MANUAL_TRADE_DETECTED"
WARNING_DRAWDOWN_CODE: str = "DRAWDOWN_WARNING"
WARNING_DAILY_LOSS_LIMIT_CODE: str = "DAILY_LOSS_LIMIT"
WARNING_CONSECUTIVE_LOSSES_CODE: str = "CONSECUTIVE_LOSSES_WARNING"
WARNING_STALE_KLINE_CODE: str = "STALE_KLINE"
WARNING_BNB_NEAR_ZERO_CODE: str = "BNB_NEAR_ZERO"
WARNING_STRATEGY_DEGRADATION_CODE: str = "STRATEGY_DEGRADATION"
WARNING_PERSISTENT_DUST_CODE: str = "PERSISTENT_DUST"
WARNING_REGIME_UNKNOWN_CODE: str = "REGIME_UNKNOWN"
INFO_STALE_BOOK_TICKER_CODE: str = "STALE_BOOK_TICKER"
INFO_STALE_BNBUSDT_CODE: str = "STALE_BNBUSDT"
INFO_DELISTING_ANNOUNCED_CODE: str = "DELISTING_ANNOUNCED"
INFO_CLOCK_DRIFT_CODE: str = "CLOCK_DRIFT"
INFO_POST_ONLY_REJECTED_CODE: str = "POST_ONLY_REJECTED"
SYMBOL_CHANGE_SELL_REASON: str = "symbol_change_flatten"
STARTUP_GAP_RISK_SELL_REASON: str = "startup_gap_risk_protection"
MISSING_BASIS_CLOSE_REASON: str = "missing_basis_close"
DELISTING_FORCE_EXIT_REASON: str = "delisting_force_exit"
TESTNET_SMOKE_GUARD_ENV: str = "MCTP_ALLOW_TESTNET_SMOKE"
STRATEGY_ID_LEGACY_EMA_CROSS: str = "legacy_ema_cross"
STRATEGY_ID_V20_BTCUSDT_MTF: str = "v20_btcusdt_mtf"
V20_MTF_BASE_TIMEFRAME_MINUTES: int = 15
V20_MTF_M15_PER_H1: int = 4
V20_MTF_M15_PER_H4: int = 16
V20_MTF_M15_PER_D1: int = 96
V20_MTF_D1_EMA_PERIOD: int = 200
V20_MTF_D1_EMA_BUFFER_PCT: Decimal = Decimal("0.01")
V20_MTF_H4_EMA_FAST_PERIOD: int = 9
V20_MTF_H4_EMA_SLOW_PERIOD: int = 21
V20_MTF_H1_RSI_PERIOD: int = 14
V20_MTF_H1_RSI_ENTRY_MIN: Decimal = Decimal("50")
V20_MTF_H1_RSI_ENTRY_MAX: Decimal = Decimal("70")
V20_MTF_H1_RSI_EXIT_MIN: Decimal = Decimal("70")
V20_MTF_REQUIRED_M15_CANDLES: int = V20_MTF_D1_EMA_PERIOD * V20_MTF_M15_PER_D1
V20_MTF_BUY_REASON: str = "v20_mtf_bullish_alignment"
V20_MTF_SELL_REASON: str = "v20_mtf_exit_signal"
